### ISSUE TITLE
add version number to ygot library package

### ISSUE THREAD

**Issue by larryleguo** [openconfig/ygot#123]

**Comment by robshakir** [comment]
Hi Lei,

I propose that we achieve this via having a tag for the version number. This should allow either gopkg.in or go dep to lock version numbers to that tag. Is this sufficient for you?

Cheers,
r.

**Comment by robshakir** [comment]
I tagged version 0.5.0 -- you can now import this via http://gopkg.in/openconfig/ygot.v0. I have tagged a couple of issues that need to be locked down for a 1.0.0 release, none of these should cause major API changes.

**Comment by larryleguo** [comment]
Thanks. Rob. Just come back from vacation. We are using govendor right now.
Let me try how the version works.

Lei

**Comment by wenovus** [comment]
Rob added modules now.
