### ISSUE TITLE
Additional data types for leafref validations.

### ISSUE THREAD

**Issue by ostromart** [openconfig/ygot#124]
- leaf-list containing leafref.
- typedef that defines a leafref.
- (for Y1.1) union that defines a leafref.

// leaf-list of leafref with a target of a leaf-ref
leaf-list foo {
 type leafref {
   path "../another-leaflist"
 }
}

leaf-list another-leaflist {
 type string;
}

"another-leaflist": ["one", "two", "three"]
"foo": ["one", "three"] // must be a subset of the other leafref.

// leaf-list of leafref with a target of a list key
leaf-list foo {
 type leafref {
   path "../a-list/key";
 }
}

list a-list {
 key "key";
 leaf key {
   type string;
 }
}

"a-list": [{"key": "one"}, {"key": "two"}]
"foo": ["one"] // must be a subset of the keys of the target list

// leaf-list of leafref with a target of a scalar leaf (probably not useful :-))
leaf-list foo {
 type leafref {
   path "../bar";
 }
}

leaf bar {
 type string;
}

"bar": "one",
"foo": ["one"] // must be equal to the target leaf, but useless to have this construct because leaf-list can only have one member

**Comment by robshakir** [comment]
This was also fixed!
