### ISSUE TITLE
unmarshaling JSON 

### ISSUE THREAD

**Issue by alshaboti** [openconfig/ygot#150]
Hi,
I got unexpected field ipv4-acl
```
"F0121 22:30:19.558646 2294 gnmi_set.go:158] Set failed: rpc error: code = InvalidArgument desc = unmarshaling json data to config struct fails: parent container device (type *ocstruct.Device): JSON contains unexpected field ipv4-acl"
```
I did compile YANG to go and in the go file the struct is 
```
type Device struct {
	Hostname	*string	`path:"hostname" module:"faucet-configuration"`
	Ipv4Acl	*FaucetConfiguration_Ipv4Acl	`path:"ipv4-acl" module:"faucet-configuration"`
}
```
I got this error when I tried to send JSON config using gnmi_set
```
{
  "hostname":"raspberrypi",
  "ipv4-acl":{
   "destination-ipv4-network": "192.168.1.0/24"
  }
}
```

I also tried with IETF JSON formate, "(faucet-configuration:ipv4-acl)"it gives same error. 

YANG module is 
```
module faucet-configuration {

  yang-version "1";

  // namespace
  namespace "http://github.com/faucetsdn";

  prefix "faucet-conf";

  import ietf-inet-types {
    prefix "inet";
  }
// from https://github.com/YangModels/yang/tree/master/experimental/ietf-extracted-YANG-modules
 import ietf-packet-fields {
    prefix packet-fields;
  }

  // meta
  organization "faucet, Inc.";

  contact
    "non";

  description
    "This module is an experimental module.";

  revision "2018-01-22" {
    description
      "Initial version";
    reference "0.0.1";
  }

  grouping faucet-top {
    description
      "top level";

    leaf hostname {
      type inet:host;
      description
        "faucet host";
    }

  container ipv4-acl {
      uses packet-fields:acl-ipv4-header-fields;
      description
           "IPv4 headers.";
      }
  }

  uses faucet-top;
}
```

**Comment by robshakir** [comment]
This doesn't look right, thanks for reporting it. Please can you provide the command-line that you used to generate the Go?

Can you also test this without using gNMI - i.e., simply using `(*Device{}).Unmarshal()` - since I think that there is also a possibility that this can be caused by the path being set incorrectly in gNMI.

Thanks,
r.

**Comment by robshakir** [comment]
Yes, this looks like it might be somewhat related to your gNMI implementation.

I generated the code with:

```
go run ~/Code/go/src/github.com/openconfig/ygot/generator/generator.go -path=$HOME/Code/ietf-yang -generate_fakeroot -output_file=oc.go -package_name=oc test.yang
```

And then ran this code example:

```
package main

import (
        "fmt"

        "robjs/ygotdebug/unmarshal/pkg/oc"
        "github.com/kylelemons/godebug/pretty"
)

func main() {

        x := &oc.Device{}
        err := oc.Unmarshal([]byte(`{
  "hostname":"raspberrypi",
  "ipv4-acl":{
   "destination-ipv4-network": "192.168.1.0/24"
  }
}`), x)

        if err != nil {
                panic(err)
        }

        fmt.Printf("%v\n", pretty.Sprint(x))
}
```

This succeeds -- i.e., `err` is `nil`. What gNMI implementation are you using around the structs?

**Comment by alshaboti** [comment]
That's greate. 
I am reusing the gnmi server used for link022
https://github.com/google/link022/blob/master/agent/gnmi/server.go

I didn't think it might be from it because if I only configure the "hostname" it works fine.

**Comment by robshakir** [comment]
That implementation doesn't seem to support the module that you've provided -- or it's not loading the right backend set of modules. If you look [here](https://github.com/google/link022/blob/master/generated/ocstruct/ocstruct.go#L67) `hostname` is actually a supported leaf from the `openconfig-office-ap` model that is supported in that implementation. I'd wager that this is why `hostname` works OK, but the `destination-ipv4-network` doesn't.

I'd recommend checking that your implementation is actually using the right backend set of generated structs.

**Comment by alshaboti** [comment]
Thank you @robshakir for your reply.

You are right. I was using another generated structs.
It works now. 

Thanks
