### ISSUE TITLE
Automatically generate a FindOrNew function for every list

### ISSUE THREAD

**Issue by VTWoods** [openconfig/ygot#161]
I see a bit of an anti pattern forming in my ygot code.  One function that works with a port calls NewInterface and future functions must check for the existence of the list element.

Example:
port, err := dev.NewInterface(portName)
if err != nil {
	return err
}

Next function that works with this interface:
port := dev.Interface[portName]
if port == nil {
	port, err = dev.NewInterface(portName)
        if err != nil {
          return err
       }
}

It would be nice if there was a helper function that would allow each caller to do:

port := dev.FindOrNewInterface(portName)

This is very similar to the Google map_util.h helper functions.
https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/map_util.h

If I have time, I might try adding this......

**Comment by robshakir** [comment]
@mum4k and I discussed this yesterday -- called `GetOrCreate` or something similar, but with exactly the behaviour you discuss here. `New<Foo>` only returns a non-nil error when the list member already exists, so we can make the signature of this new function not need to return an `error`. I've got the start of a CL to add this in progress (although, contributions of course are welcome!) :-)

**Comment by VTWoods** [comment]
SGTM.  I will look for your CL so I can learn how to add a new generated function in the future.
