### ISSUE TITLE
unmarshalLeaf cannot parse empty JSON leaf

### ISSUE THREAD

**Issue by CmeRR4** [openconfig/ygot#186]
I've generated go representation of a YANG module that has "empty" type leaf,
As a result generator.go converted that "empty" type leaf into "YANGEmpty" type which is bool.
When i'm trying to unmarshall this leaf from JSON to gostruc I'm getting the following error:
( got []interface {} type for field test1, expect bool ) which is coming from unmarshalLeaf function.

Yang:
 leaf test1 {
    type empty;
}

JSON request:
{
  "test1": [null]
}

I was trying to pass different JSON, set the value to "true" since it is bool type in gostuct,
and also other versions of the JSON message, however, it does not work and the unmarshaller
cannot parse this type of "YANG leaf".

Is it supported to use "empty" type leafs? And how should I use it?

**Comment by robshakir** [comment]
Thanks for the bug. PTAL at the code in the `unmarshal-empty` branch that will resolve this issue. It looks to have been an omission when we implemented `empty` originally.
