### ISSUE TITLE
Unable to work with global enums

### ISSUE THREAD

**Issue by shravyarani** [openconfig/ygot#228]
Hi All,

I have created a basic_types.yang file with typedef enum in it and I am using it in multiple files. The protos generated using ygot. However, when I compile code it throws errors saying enum package is not defined.

com/test/core/datamodel/protos/common/common.proto:121:3: "com.test.core.datamodel.protos.common.enums.SwitchState" is not defined.

local enums doesn't have this issue.

**Comment by robshakir** [comment]
Hi,

Can you provide the arguments that you're using to generate the protos, and protoc please?

Thanks,
r.

**Comment by wenovus** [comment]
I think this may be due to #394

**Comment by wenovus** [comment]
Optimistically closing.
