### ISSUE TITLE
Deviation is not supported

### ISSUE THREAD

**Issue by bovenyan** [openconfig/ygot#233]
Seems ygot currently doesn't support deviation. This creates some inconvenience to provide full feature support for vendors that has deviations compare to a standard OpenConfig Yang model. 
Is it one of the task being worked on? 

Thanks,
Bo

**Comment by robshakir** [comment]
Hi Bo,

Thanks for the message.

You're right, we don't currently support deviation. This is something that is on our TODO list, but we hasn't yet bubbled to the top. We're happy to guide work on this if you'd like to contribute code!

Cheers,
r.

**Comment by bovenyan** [comment]
> Hi Bo,
> 
> Thanks for the message.
> 
> You're right, we don't currently support deviation. This is something that is on our TODO list, but we hasn't yet bubbled to the top. We're happy to guide work on this if you'd like to contribute code!
> 
> Cheers,
> r.

Would love to contribute. Thanks for the guidance. Will push a pull request. 

Bo

**Comment by robshakir** [comment]
For reference, a change to add deviation support deviation in goyang is in https://github.com/openconfig/goyang/pull/83.

**Comment by robshakir** [comment]
Hi,

Deviation is now supported by ygot -- closing this issue :-)

Thanks,
r.
