### ISSUE TITLE
-enum_package_name is ignored?

### ISSUE THREAD

**Issue by seiferteric** [openconfig/ygot#271]
When passing the option -enum_package_name to proto_generator it seems to be ignored, and all the enums end up in the same package with the default name. Furthermore the enumPackageName does not seem to be used.

Also, if you run proto_generator multiple times with different values for -enum_package_name, it will overwrite the previous enum package.

**Comment by robshakir** [comment]
Thanks for the report -- this looks like the `enum_package_name` wasn't being passed through to `ygen`. PTAL at #272.

`proto_generator` writes entire protobuf files out, we don't read to check whether there is a header and append. To combine modules together, run `proto_generator` with all of the packages you wish to generate together.

Cheers,
r.
