### ISSUE TITLE
Help wanted: 'augment' already set

### ISSUE THREAD

**Issue by iadak** [openconfig/ygot#274]
Hello,

Is the following a known issue?

```
go run ygot/generator/generator.go -ygot_path=. -path=yang/UTD/1693 -output_file=pkg/src/lib/isr/utd.go -package_name=utd -generate_fakeroot -compress_paths=true ./yang/UTD/1693/Cisco-IOS-XE-utd.yang
F0307 08:42:37.171636   30089 generator.go:261] ERROR Generating Code: augment: already set
exit status 1
```

I see the problem using the file with or without the dependencies. Is there a way to debug ygen and see which "augment" actually causing this issue?

Original Yang model could be found here.
https://github.com/YangModels/yang/blob/master/vendor/cisco/xe/1693/Cisco-IOS-XE-utd.yang
I am assuming that the model is correct as it is consumed by Netconf in production.

Regards
Indranil

**Comment by robshakir** [comment]
The issue is caused by the `augment` at line 996 of this file (`augment web-filter`).  This module appears to be YANG 1.0 -- and includes this construct:

```
            uses utd-engine-standard-grouping {
              augment threat-inspection {
                uses utd-engine-threat-inspection-grouping;

                leaf whitelist {
                  description
                    "Enable whitelisting under the utd engine";
                  type empty;
                }
              }
              augment web-filter {
                leaf domain-profile {
                  description
                    "Choose the domain profile to use for web filtering";
                  type string {
                    length "1..512";
                  }
                }
                leaf url-profile {
                  description
                    "Choose the url profile to use for web filtering";
                  type string {
                    length "1..512";
                  }
                }
              }
            }
```

Note that this is `uses .. { augment { ... } augment { ... } }` -- which according to [RFC6020](https://tools.ietf.org/html/rfc6020#section-7.12.1) is not legal (expressed cardinality of `augment` within `uses` is `0..1`). YANG 1.1 changes this cardinality to be `0..n`, but this isn't something that we support today.

Cisco should probably set the `yang-version` correctly in this module -- such that this can be identified, or fix this module to actually be YANG 1.0 compatible. We're tracking the discussions about Y1.1 support for this cardinality in [this issue](https://github.com/openconfig/goyang/issues/51).

**Comment by iadak** [comment]
Thank you Rob for your quick response. I have understood the limitation. Basically, even if I make the model 1.1 compliant, the current code would still not be able to parse it. Anyway, let me see if I can fix the model to achieve my objective.

Thanks again
Indranil

**Comment by robshakir** [comment]
We're discussing how best to support these differences between Y1 and Y1.1 in our code-base, but haven't actually had much demand for the backwards-incompatible changes like this cardinality change -- I'm not really sure whether this model is intentionally written this way, or it is a bug.

If you comment out one of the `augment` statements within the `uses`, or work out how to combine them, then this model is generated fine.

BTW -- `compress_paths` will NOT work with this module, it is designed only to work with OpenConfig modules. ygot'll likely throw an error or panic.

**Comment by iadak** [comment]
Thank you Rob. We had been able to generate the "go" structure by following the suggestions provided in [issue 51](https://github.com/openconfig/goyang/issues/51). Now, we're trying to retrofit the Yang model represented in XML message with the generated "go" structure.  We see that there're unmarshal routines generated by "ygot", which takes JSON input. Will you be able to provide any suggestion that can help us achieve that? E.g. 

ygot(yang) -> go structs <- ? <- XML <- netconf(yang)
