### ISSUE TITLE
Go mod support

### ISSUE THREAD

**Issue by h7kanna** [openconfig/ygot#288]
Hi, 
Any plan to support Go > 1.11 with module support?

Thanks,

**Comment by h7kanna** [comment]
Also please use semantic version for tags
Currently release v0.6.0 is tagged as 0.6.0 which go mod is not able to use.

**Comment by robshakir** [comment]
Thanks -- I fixed the tag, apologies for this error.

Thus far, I haven't looked into Go module support, happy to discuss what we need to implement to support this.

**Comment by h7kanna** [comment]
Hi, Thanks for the fix. For now, as the release is below 1.0.0 correct semantic version tag would suffice.

**Comment by wenovus** [comment]
This has been fixed by @robshakir.
