### ISSUE TITLE
ygotutils get node and namespaces in the path

### ISSUE THREAD

**Issue by adibrastegarnia** [openconfig/ygot#300]
Hi, 
I have a quick question: I would like to know if a path has namespaces in the elements, can the following function retrieve its node?
`node, stat := ygotutils.GetNode(s.model.schemaTreeRoot, s.config, fullPath)`

Here is the function to generate the full path:
```
// GnmiFullPath builds the full path from the prefix and path.
func GnmiFullPath(prefix, path *pb.Path) *pb.Path {
	fullPath := &pb.Path{Origin: path.Origin}
	if path.GetElement() != nil {
		fullPath.Element = append(prefix.GetElement(), path.GetElement()...)
	}
	if path.GetElem() != nil {
		fullPath.Elem = append(prefix.GetElem(), path.GetElem()...)
	}
	return fullPath
}
```

Thanks,
Adib

**Comment by robshakir** [comment]
No, we do not support using namespaces in the path in gNMI.

**Comment by robshakir** [comment]
Throughout ygot, we make the simplifying assumption that there are not overlapping names of nodes within the same context, such that there's no need to have namespaces within the path. In practice, this seems to be true everywhere, and the developer experience of having namespaces be everywhere seems suboptimal.

Given that this assumption is made throughout gNMI -- including in the path conventions -- then I don't think that we want to add some handling for namespaces here. If there are clear use cases for having this, then we should discuss that in the context of gNMI.

r.

**Comment by adibrastegarnia** [comment]
@robshakir 
Thanks for your quick response. Let me check with the group and then update you accordingly. The reason that I asked it is because of this issue that I should address but I think it is dependent to ygotutils.GetNode function. 
[(https://github.com/onosproject/simulators/issues/67)]

**Comment by adibrastegarnia** [comment]
Resolved (We addressed in our side)
