### ISSUE TITLE
issues with getting started

### ISSUE THREAD

**Issue by thilak07** [openconfig/ygot#301]
In the following example section, is producing an error. ygot.ValidatedGoStruct takes a pointer.

json, err := ygot.EmitJSON(d, &ygot.EmitJSONConfig{
	Format: ygot.RFC7951,
	Indent: "  ",
	RFC7951Config: &ygot.RFC7951JSONConfig{
		AppendModuleName: true,
 	},
})

./ocinterface.go:29:29: cannot use d (type ocdemo.Device) as type ygot.ValidatedGoStruct in argument to ygot.EmitJSON:
	ocdemo.Device does not implement ygot.ValidatedGoStruct (IsYANGGoStruct method has pointer receiver)
using a pointer to d works as expected.

**Comment by robshakir** [comment]
`d` is declared to be a pointer in the getting started example: https://github.com/openconfig/ygot/blob/master/demo/getting_started/interfaces.go#L36

Is the `ocinterfaces.go` file that you're referencing here something that you have written?

Thanks,
r.

**Comment by thilak07** [comment]
Thanks, Rob, I see the problem now. I wrote 'ocinterfaces.go' and didn't use a pointer for the fake root.
