### ISSUE TITLE
ResolveIfLeafRef encounters Error when node contains predicates

### ISSUE THREAD

**Issue by gsindigi** [openconfig/ygot#305]
When trying to resolve a leaf reference using `util.ResolveIfLeafRef`, it encounters an error when the node.Type.Path do contain a predicate in it, which results in incorrectly deducing a non-existent key name for refSchema.Dir lookup. 

__Working case__:
path: /oc-if:interfaces/oc-if:interface/oc-if:name
Resolved Leafref &{0xc00177f680 <nil> name    [] Leaf unset 0xc001771810 unset map[]  0xc00177cee0 [] <nil> <nil> [] [] [] [] map[] [] map[] map[] <nil>}

__Error case__:
path: /oc-if:interfaces/oc-if:interface[oc-if:name=current()/../interface]/oc-if:subinterfaces/oc-if:subinterface/oc-if:index
Couldnt resolve leafref ***schema node name=current() is nil for leafref schema subinterface with path /oc-if:interfaces/oc-if:interface[oc-if:name=current()/../interface]/oc-if:subinterfaces/oc-if:subinterface/oc-if:index***

In the error case, I think the look up should have been done for "interface"; instead, it does look up using "name=current()" and errs out.  The `path`  used inside `findLeafRefSchema` called by `ResolveIfLeafRef` contain values as {"", "oc-if:interfaces", "oc-if:interface[oc-if:name=current()", "..", "interface]", "oc-if:subinterfaces", "oc-if:subinterface", "oc-if:index"}

If I were to guess, this could be for the cases where the yang nodes do contain a predicate to the referred nodes.   The schema used in here is generated using `network-instance/openconfig-network-instance.yang`.

**Comment by wenovus** [comment]
This might be solved by #304 where util's `findLeafRefSchema()` has been replaced by `findLeafRefSchema()` in ytypes/leaf.go, and where removeXPATHPredicates() is called on the path prior to processing. Let me see if I can add a unit test.
