### ISSUE TITLE
Question about gnmi_get and Unmarsha JSON_IETF

### ISSUE THREAD

**Issue by thilak07** [openconfig/ygot#320]
I am using GetJsonIetfVal()on pb.Update inside a GetRespose.Notification and, I am able to the JSON payload coming back from the node.
Is there a method to Unmarshell and assign this payload to YANG go struct (ygot generated bindings)? I am not able to see the go struct getting populated with the JSON data.

For example,
gNMI Get for xPath "openconfig-interfaces:interfaces/"

for _, pbNotification := range GetRespose.Notification {
	for _, update := range pbNotification.GetUpdate() {
		InterfaceByteVal := val.GetJsonIetfVal() <<<<<<<<<<<<<
ocInterface := &yangmodels.Interface{} // /openconfig-interfaces/interfaces/interface YANG schema element.

err = json.Unmarshal(InterfaceByteVal, ocInterface)

**Comment by wenovus** [comment]
You can unmarshal updates using `ytypes.SetNode` given the goStruct, the goStruct's schema, the path of the update, and the TypedValue inside the Update message.

**Comment by thilak07** [comment]
Thank you @wenovus !.  Can you provide an example to use ytypes.SetNode to umarshal ?

**Comment by wenovus** [comment]
Based on your example, *assuming* the update paths are absolute paths, I would expect something similar to this,
```
ocInterface := &yangmodels.Interface{}
structSchema := yangmodels.SchemaTree["Interface"]
structPath := util.PathStringToElements(structSchema.Path())[1:] // May have to tweak this. This excludes the module or fakeroot element.
for _, pbNotification := range GetRespose.Notification {
  for _, update := range pbNotification.GetUpdate() {
    // SetNode expects the relative path of the update from the GoStruct that's passed in for unmarshalling.
    relPath := util.TrimGNMIPathPrefix(update.GetPath(), structPath)
    if relPath == update.GetPath() {
        return "error -- not a prefix"
    }
    err := ytypes.SetNode(structSchema, ocInterface,  relPath, update.GetVal(), &ytypes.InitMissingElements{})
  }
}

return ocInterface
```
gNMI Get returns a set of leaf updates under the request path, so SetNode should be called on each update to reconstruct the entire node.

**Comment by wenovus** [comment]
Oops, looks like I didn't read the README and didn't get that you were trying to unmarshal JSON -- you may have already found this but here is the link:
https://github.com/openconfig/ygot#unmarshalling-json-to-a-gostruct

**Comment by thilak07** [comment]
Thank you @wenovus!
