### ISSUE TITLE
UnMarshal failing with nested list in the yang

### ISSUE THREAD

**Issue by Ragavakumar** [openconfig/ygot#357]
I created a YANG file that has nested list similar to   "Interface " and "Subinterface " structure members of "Device" and "Interface" structures from the demo. When the any parameter of the subinterface is populated we are getting an error " got type map[string]interface {}, expect []interface{}".

**Comment by Ragavakumar** [comment]
Actual Error received: 
: jsonList map[eth0:map[config:map[description:An Interface mtu:1500 name:eth0] name:eth0 state:map[admin-status:UP] subinterfaces:map[subinterface:map[10:map[co...: got type map[string]interface {}, expect []interface{}

**Comment by robshakir** [comment]
We only support unmarshalling RFC7951 format JSON - it looks like you
rendered the internal format, which uses maps for lists rather than slices.

Cheers,
r.

**Comment by Ragavakumar** [comment]
Thanks. When I used the RFC7951 format using ygot.EmitJson API, received the following error. 
_UnMarshal:  unmarshalContainer for schema device: jsonTree {
  "config": {
    "description": "An Interface",
    "mtu": 1500,
    "name": "eth0"
  },
  "name": "eth0",
  "state": {
    "admin-status": "UP"
  ...: got type string inside container, expect map[string]interface{}_

The code I used is pasted below: 
```
     jon, err := ygot.EmitJSON(device.Interface["eth0"], &ygot.EmitJSONConfig{
        Format: ygot.RFC7951,
        Indent: "  ",
        RFC7951Config: &ygot.RFC7951JSONConfig{
                AppendModuleName: false,
        },
})
   nb, err := json.Marshal(jon)
    loadd := &oc.Device{}
            err = oc.Unmarshal(nb, loadd)
            if err != nil {
               fmt.Println("UnMarshal: ", err)
               return
            }

```

**Comment by robshakir** [comment]
You don't need to JSON marshal the result of EmitJSON. Per the
documentation it returns a string.

You're also trying to unmarshal the interface list into the root struct.
I'd encourage you to look further at the examples and tests in the repo.

r.

**Comment by Ragavakumar** [comment]
Thanks Rob. One query, is there an API to convert from internal format to RFC7951 format JSON?  I need to convert the received gnmiPaths to the goStruct. I wrote logic to convert PATHs to internal JSON format. Or is there a way to convert directly from gnmiPaths to goStructs?
