### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by sachinholla** [openconfig/ygot#363]
go get of ygot is failing since few days. Probably after commit 40a57e464acae3a5ea401b2c8a85e879540a092f.

```
~$ GOPATH=/tmp/go go get github.com/openconfig/ygot/ygot
# github.com/openconfig/gnmi/proto/gnmi_ext
src/github.com/openconfig/gnmi/proto/gnmi_ext/gnmi_ext.pb.go:47:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4
# github.com/openconfig/ygot/proto/yext
src/github.com/openconfig/ygot/proto/yext/yext.pb.go:44:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4
# github.com/openconfig/ygot/proto/ywrapper
src/github.com/openconfig/ygot/proto/ywrapper/ywrapper.pb.go:46:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4
~$ go version
go version go1.12.5 linux/amd64
```

**Comment by robshakir** [comment]
This seems like your proto packages are out of sync -- can you try "go get
github.com/openconfig/ygot" rather than the subpackage?

Thanks,
r.

**Comment by sachinholla** [comment]
hi Rob, that is not working either. Note that I am starting with an empty gopath directory /tmp/go.

```
~$ GOPATH=/tmp/go go get github.com/openconfig/ygot
package github.com/openconfig/ygot: no Go files in /tmp/go/src/github.com/openconfig/ygot
```

**Comment by robshakir** [comment]
Hey Sachin,

It looks like this is because go1.12.x doesn't have the new Go modules on by default. If you specify `GO111MODULE=on`, then the new module code is used and this will work as expected.

The reason that it doesn't work otherwise is that it doesn't honour the right version of the protobuf library supporting the new Proto API [described here](https://blog.golang.org/protobuf-apiv2).

Cheers,
r.

**Comment by wenovus** [comment]
Yes this is strange. Even with Go 1.14 I see this message. This is despite the FAQ here:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#enforce-version-apiv1
`go test ./...` still works so maybe this is not a practical issue.

**Comment by robshakir** [comment]
That latter message is expected (sorry, I misread it before).

The reason you see it (as you do with `github.com/golang/protobuf` is that the repo contains no `.go` files at the root -- so that means we don't have anything that can be built when you do `go build` in that dir. 

It's not actually indicative of anything being wrong:

```
[15:21] ~                                                                      
▶ go get -u github.com/openconfig/ygot
package github.com/openconfig/ygot: no Go files in /Users/robjs/tmp/gopath/src/github.com/openconfig/ygot

[15:21] ~                                                                     ⍉
▶ echo $?
1

[15:21] ~                                                                      
▶ go get -u github.com/golang/protobuf
package github.com/golang/protobuf: no Go files in /Users/robjs/tmp/gopath/src/github.com/golang/protobuf

[15:21] ~                                                                     ⍉
▶ echo $? 
1
```

**Comment by wenovus** [comment]
`GO111MODULE=on GOPATH=/tmp/go go get github.com/openconfig/ygot/...` no longer gives the error. I don't really know why, but I guess now that we've moved to modules I think it's ok to require this as the command.

**Comment by wenovus** [comment]
An new issue here is we haven't tagged ygot in a while, and without a `@master` you will download the last tag with modules turned on, which is not the behaviour we want.

@robshakir should we add a new tag for ygot? It seems necessary with modules.

**Comment by robshakir** [comment]
Sounds a good idea. It looks like we are stable @ HEAD right now. Shall we
tag this 0.7.0?

r.

**Comment by wenovus** [comment]
Done
