### ISSUE TITLE
Generate Proto file or Java

### ISSUE THREAD

**Issue by brindasanth** [openconfig/ygot#369]
Hi Team,
I am working on GNMI Java interface, Is there any way we can generate proto file from Yang not the go proto struct ? So that I can use the other tool to generate java from proto for Open Config YANG model.

**Comment by robshakir** [comment]
hi!

Yes, you can use the `protogenerator` package that is in this repo. There is some [getting started documentation](https://github.com/openconfig/ygot/blob/master/docs/protobuf_getting_started.md) available here.

cheers,
r.

**Comment by brindasanth** [comment]
Thanks a lot.
