### ISSUE TITLE
Any means to convert gnmi.Notification to related GoStructs?

### ISSUE THREAD

**Issue by gsindigi** [openconfig/ygot#373]
Similar to the library func `ygot.TogNMINotifications`, is there any func to achieve set of `Notification`s to related `GoStruct`s?  When I tried to come up with a generic way to achieve this, came across certain challenges e.g., as Notification encodes primitve types in generic Typed_U/Int_Vals, its difficult determine the actual datatype of the leaf entity.  This needs reflection and YANG-Schema based inspection similar to the way its done in `TogNMINotifications`.   I could not find any exported functions in the library.   Possible that, I could be overlooking.  If so, please point me to the same.  Otherwise, are there any means to achieve this  so that it fits and leverages existing code?  Thanks.

**Comment by robshakir** [comment]
You can use `ytypes.SetNode` ([godoc](https://github.com/openconfig/ygot/blob/master/ytypes/node.go#L428)) which allows you to hand the root, along with the gNMI `Path` message and the value that you have. This allows unmarshalling of gNMI Notifications into a generated struct.

**Comment by soumiksamanta** [comment]
Thanks @robshakir . I had a similar issue while using ygot.Diff. I wanted to apply the notification produced, to the original GoStruct object.

**Comment by wenovus** [comment]
There is a `ygot. MergeStructInto ` ([godoc](https://github.com/openconfig/ygot/blob/master/ygot/struct_validation_map.go#L507)) that allows you to merge the fields of a different struct into the original GoStruct. Does that do what you want to achieve?

**Comment by soumiksamanta** [comment]
@wenovus  My requirement is to generate the notification using the diff and apply selected updates and/or deletes on the original struct.
Thanks for the tip though. `MergeStructInfo` can be used if I had to merge the entire modified GoStruct to the original GoStruct.

**Comment by boisjacques** [comment]
Has there been any development? I'm trying to solve the same problem as @gsindigi and I keep running into errors with the approach @robshakir suggested.

The following line is my approach but I don't know if that's the correct one:
```go
root := oc.Device // The fake root generated by ygot
path := response.Notification[0].Update[0].Path // 
val := response.Notification[0].Update[0]
opts := []ytypes.SetNodeOpt{&ytypes.InitMissingElements{}, &ytypes.TolerateJSONInconsistencies{}}

ytypes.SetNode(schema, root, path, val, opts...)
```

response is a response to a Get `interfaces-interface` and yields this error: 

`rpc error: code = InvalidArgument desc = could not find schema for type *openconfig.Device, field Acl`
