### ISSUE TITLE
MergeStructInto does not support overwrite

### ISSUE THREAD

**Issue by soumiksamanta** [openconfig/ygot#418]
If the dstField is set, ideally MergeStructInto should overwrite the value from src

```
if !util.IsNilOrInvalidValue(dstField) {
	s, d := srcField.Elem().Interface(), dstField.Elem().Interface()
	if diff := cmp.Diff(s, d); diff != "" {
		return fmt.Errorf("destination value was set, but was not equal to source value when merging ptr field, (-src, +dst):\n%s", diff)
	}
}
```

There are usecases when one want to merge the dst struct from src struct, adding and updating the fields. 

Is this outside the scope of the `MergeStructInto`?

**Comment by wenovus** [comment]
This doesn't seem to be supported, although it can definitely be implemented. @robshakir are you ok with adding a helper here?

For now, a workaround is perhaps to call [ygot.TogNMINotifications](https://pkg.go.dev/github.com/openconfig/ygot/ygot?tab=doc) on the srcStruct, and then looping over the `Update` field, calling [ytypes.SetNode](https://pkg.go.dev/github.com/openconfig/ygot/ytypes?tab=doc) for each `Path` and `Val` for each `Update` on the destStruct. I admit this may not work and is not ideal, but it may serve what you need.

**Comment by robshakir** [comment]
Hi!

This was the requested behaviour of the consumer of this API that we implemented this call for initially -- in their use case, there was an explicit need for an error when two fields were set to unequal values. 

I suggest that the right way to add this is to add a `MergeOpt` (in a similar manner to the `DiffOpt` that we have today) that gives us a way to control whether overwriting is performed - and then plumb this through the code such that we check it before doing the diff quoted in the OP.

We should ensure to add unit tests for this case too. 

@soumiksamanta -- Wen or I can review a submission on this if you'd like to make a PR. We can also discuss the design further here if you'd like.

Cheers,
r.

**Comment by soumiksamanta** [comment]
Thanks @robshakir @wenovus I will run through the current behavior and try to introduce the `MergeOpt`. I will definitely get back to you if I hit a roadblock.
