### ISSUE TITLE
Potential Data Race in experimental ygotutils 

### ISSUE THREAD

**Issue by adibrastegarnia** [openconfig/ygot#455]
I noticed sometimes when there are multiple goroutines call GetNode function, there is invalid memory error in this line of code:
https://github.com/openconfig/ygot/blob/master/experimental/ygotutils/common.go#L525 

I think there is a data race for that global variable which leads to this error:
For more information, please refer to this issue

https://github.com/onosproject/gnxi-simulators/issues/102

**Comment by wenovus** [comment]
Hi Adib, the experimental directory is completely deprecated, instead you should use the `GetNode` from `ytypes`: https://github.com/openconfig/ygot/blob/master/ytypes/node.go#L361

**Comment by adibrastegarnia** [comment]
@wenovus 
Yeah I migrated our simulator to use the new API instead and it is working fine.
