### ISSUE TITLE
ygot generates error for IETF Alarams yang model

### ISSUE THREAD

**Issue by adibrastegarnia** [openconfig/ygot#470]
I was trying to use ygot to generate the model for ietf-alarms@2019-09-11 but I am getting the following error

`F1116 14:20:32.825026   98802 generator.go:333] ERROR Generating GoStruct Code: unknown type of entry Directory in findMappableEntities for /ietf-alarms, unknown type of entry Directory in findMappableEntities for /ietf-alarms, unknown type of entry Directory in findMappableEntities for /ietf-alarms/alarms/alarm-list/alarm
exit status 1
ygot failed`
Any ideas?

**Comment by wenovus** [comment]
Hi Adib,
There is probably an unsupported child node under `/ietf-alarms/alarms/alarm-list/alarm` -- I'm not aware of ygot's support of any of `notification` and `action` nodes.

The error message is unclear, I will open a PR to fix it.

**Comment by adibrastegarnia** [comment]
> Hi Adib,
> There is probably an unsupported child node under `/ietf-alarms/alarms/alarm-list/alarm` -- I'm not aware of ygot's support of any of `notification` and `action` nodes.
> 
> The error message is unclear, I will open a PR to fix it.
@wenovus 
That would be great.
