### ISSUE TITLE
Inconsistent Generated proto enum Names

### ISSUE THREAD

**Issue by wenovus** [openconfig/ygot#471]
https://developers.google.com/protocol-buffers/docs/style#enums
```
enum FooBar {
  FOO_BAR_UNSPECIFIED = 0;
  FOO_BAR_FIRST_VALUE = 1;
  FOO_BAR_SECOND_VALUE = 2;
}
```

The underscores are currently omitted in the generated protos.

**Comment by robshakir** [comment]
Hey @wenovus -- I think today they follow /something/ akin to this style -- essentially the difficulty one has is that you need to be able to do something that makes sense to the user consistently.

If we use [this example](https://github.com/openconfig/gribi/blob/master/proto/gribi_aft/enums/enums.proto) - the current pattern is `<module>_<path element 1>_<path element 2>_..._<last path element>`. I assume that here you're concerned that the naming is not converting `foo-bar` into `FOO_BAR` but rather `FOOBAR` for an individual element? Do you have an example of where this is causing concern?

**Comment by wenovus** [comment]
I was only considering the style guide and posted the issue. Looking at it more now, I agree whether the underscore exists is just a minor concern as long as things are consistent.

However, I now notice that there is an inconsistency in the naming where ["valuePrefix"](https://github.com/openconfig/ygot/blob/master/ygen/enumgen.go#L139) is used as the enum name prefix for enumeration-in-union (both inlined & typedef) instead of the regular-assigned enum name (https://github.com/openconfig/ygot/blob/master/ygen/protogen.go#L832). I wonder why that is, because I don't see what this special case gives us. It actually makes typedef enumeration-in-union names unpredictable, because the "valuePrefix" becomes the first path where the typedef is used. It's also inconsistent since underscores are given to them (e.g. `GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_UNSET` in your example).

I don't have a strong preference whether to have underscores in the prefix part of the name, but I think for consistency, I would propose to remove the "valuePrefix" logic. e.g. for the example you've provided, removing the logic (with -typedef_enum_with_defmod=true for both cases) would give this:

```
@@ -24,13 +24,13 @@ enum OpenconfigAftTypesEncapsulationHeaderType {

 // OpenconfigMplsTypesMplsLabelEnum represents an enumerated type generated for the YANG enumerated type mpls-label.
 enum OpenconfigMplsTypesMplsLabelEnum {
-  GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_UNSET = 0;
-  GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IPV4_EXPLICIT_NULL = 1 [(yext.yang_name) = "IPV4_EXPLICIT_NULL"];
-  GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_ROUTER_ALERT = 2 [(yext.yang_name) = "ROUTER_ALERT"];
-  GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IPV6_EXPLICIT_NULL = 3 [(yext.yang_name) = "IPV6_EXPLICIT_NULL"];
-  GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_IMPLICIT_NULL = 4 [(yext.yang_name) = "IMPLICIT_NULL"];
-  GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_ENTROPY_LABEL_INDICATOR = 8 [(yext.yang_name) = "ENTROPY_LABEL_INDICATOR"];
-  GRIBIAFT_AFTS_MPLS_LABELENTRY_CONFIG_LABEL_NO_LABEL = 9 [(yext.yang_name) = "NO_LABEL"];
+  OPENCONFIGMPLSTYPESMPLSLABELENUM_UNSET = 0;
+  OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV4_EXPLICIT_NULL = 1 [(yext.yang_name) = "IPV4_EXPLICIT_NULL"];
+  OPENCONFIGMPLSTYPESMPLSLABELENUM_ROUTER_ALERT = 2 [(yext.yang_name) = "ROUTER_ALERT"];
+  OPENCONFIGMPLSTYPESMPLSLABELENUM_IPV6_EXPLICIT_NULL = 3 [(yext.yang_name) = "IPV6_EXPLICIT_NULL"];
+  OPENCONFIGMPLSTYPESMPLSLABELENUM_IMPLICIT_NULL = 4 [(yext.yang_name) = "IMPLICIT_NULL"];
+  OPENCONFIGMPLSTYPESMPLSLABELENUM_ENTROPY_LABEL_INDICATOR = 8 [(yext.yang_name) = "ENTROPY_LABEL_INDICATOR"];
+  OPENCONFIGMPLSTYPESMPLSLABELENUM_NO_LABEL = 9 [(yext.yang_name) = "NO_LABEL"];
 }
```

**Comment by robshakir** [comment]
Yes, I think you're right -- moving away from `valuePrefix` here sounds like the right thing to do. It sounds like the existing `typedef_enum_with_defmod` would give us a flag to be able to control this?
