### ISSUE TITLE
replacement of NewNode function in expermintal ygotutils

### ISSUE THREAD

**Issue by adibrastegarnia** [openconfig/ygot#477]
What is the replacement of this function call:
```
	rootNode, stat := ygotutils.NewNode(m.structRootType, &pb.Path{})
```

**Comment by wenovus** [comment]
Good question! @robshakir I took a look and it looks like there is no close relative of this function in existing code.

One workaround I see is to do a `ytypes.GetOrCreateNode` on a new instance of `m.structRootType`'s type. The schema is required, which you get get via `oc.SchemaTree["<name of structRootType>"]`, which gives more robust error checking.

**Comment by adibrastegarnia** [comment]
@wenovus 
That function is used in the target (our simulator) like what you have in gnxi tools. A few months ago, I migrated some of the function calls from ygotutils to use ytypes but I couldn't find something similar for that one. We also use vendoring for some of our repos and version mismatch will be problematic since ygotutils removed from the latest version. 

I need these two be replaced to make migration complete in our gnmi target. 
https://github.com/google/gnxi/blob/master/gnmi/model.go#L61
https://github.com/google/gnxi/blob/master/gnmi/server.go#L186

If you want to replace them using the workaround, how you will do that?

**Comment by adibrastegarnia** [comment]
@wenovus 
Thanks for opening that PR.
