### ISSUE TITLE
[Help Wanted]: How do we use the ygot package to persist the validated yang data into the database.

### ISSUE THREAD

**Issue by KBA07** [openconfig/ygot#520]
Is there a way to generate Gorm or any database ORM modeling using Ygot as of now? 

If it is, then can you help me figure this out. If not then how are you persisting the yang config as of now to the database?

Furthermore, If the modeling doesn't exist as of now. Are you planning to support this in the future?

**Comment by wenovus** [comment]
Hi Kashif, unfortunately I haven't looked into this. Just as a first thought, I'm wondering if you could store a serialized version of the `GoStruct`s by marshalling them to JSON?

**Comment by robshakir** [comment]
Today, there isn't any specific hook into an ORM model that ygot's structs provide. There are various means of persisting their contents, either using approaches like marshalling to JSON, gob etc., or breaking out the values and storing `<path, value>` pairs in some KV storage.

We'd be happy to discuss what the requirements would be to integrate with a backend storage mechanism if you have specific design thoughts, and we can review changes that implement this following that design discussion.

Thanks,
r.

**Comment by KBA07** [comment]
Okay, First of all do you have a discord, slack, telegram, whatsapp channel/group. It would be easier for me to communicate with you guys over there.

**Comment by robshakir** [comment]
Closing this issue as it appears to be answered. Please re-open the issue if there's any further discussion you'd like to have with the ygot team :-)
