### ISSUE TITLE
ygot Diff output conversion to GoStruct

### ISSUE THREAD

**Issue by adelshafiei** [openconfig/ygot#577]
I would like to convert the output of ygot.Diff (gnmi.Update Update and gnmi.Path Delete) to two GoStruct. Does ygot currently support that?
Possible option: ygot.Diff to support encoding
If ygot Diff would provide a way to specify gnmi Encoding, I could ask for JSON IETF encoding and then, I would be able to easily convert to GoStruct by unmarshalling the output after a few small tweaks:
	config := "{"
	for _, n := range resp.GetNotification() {
		for _, u := range n.GetUpdate() {
			ps, err := ygot.PathToString(u.GetPath())
			if err != nil {
				// handle error
			}
			config += fmt.Sprintf("%q: %s,", ps, u.Val.GetJsonIetfVal())
		}
	}
	config = strings.TrimSuffix(config, ",")
	config += "}"
	var device gen.Device
	if err := gen.Unmarshal([]byte(config), &device); err != nil {
		// handle error
	}
However, the above cannot work with the current implementation of ygot.Diff.
Any other ways to get goStruct from gnmi.Notification?

**Comment by wenovus** [comment]
You can unmarshal `TypedValue`-encoded values one-by-one using `ytypes.SetNode`:
https://github.com/openconfig/ygot/blob/926dd30e27e4e617ac641e0ee02d9c9fb23bbc73/ytypes/node.go#L502

The `schema` can be retrieved via `GoStructPkg.SchemaTree`.

` SetNode(schema, goStructPtr, update.Path, update.Val, sopts...)`

**Comment by adelshafiei** [comment]
Great help! Thank you. I tried and it worked fine. We can close this issue.
