### ISSUE TITLE
Is there an option to add auto generated code to populate proto struct from/to go struct ?

### ISSUE THREAD

**Issue by MUlan2004** [openconfig/ygot#587]
So there are two generators:

1. proto_generator - that generates <some_yang>.proto files
2. generator - that generates <some_yang>.go files

After running protoc on .proto files we have another set of auto generated Go code to hold the same data but in slightly different layout. Is there a way to automatically populate message proto structs from Go structs ? For example some devices return Update values as JSON that can be unmarhsalled into Go struct without much trouble, however I'd like to store data as a protos in some persistent backend that supports protos natively (something like Spanner), so code path would be like JSON -> Go Struct -> proto message when processing from device and reverse when pushing config to the device. proto from datastore -> Go Struct -> JSON value to the device.

I wonder if it's possible to add flag to generate methods for Go structs to emit corresponding proto messages as well as populate Go struct from corresponding proto message.

**Comment by wenovus** [comment]
You can try this for a GoStruct -> proto conversion:
https://github.com/openconfig/gribigo/blob/311f603596062288ec28d0ef45855ca7dd5b7317/rib/rib.go#L1476-L1502

As for the reverse you can try calling `PathsFromProto` and then `ytypes.SetNode` on the GoStruct.

[godoc for protomap](https://pkg.go.dev/github.com/openconfig/ygot/protomap)

**Comment by MUlan2004** [comment]
Thanks! I think that's what I needed!
