### ISSUE TITLE
How to pass all the files in a folder to go generate?

### ISSUE THREAD

**Issue by adelshafiei** [openconfig/ygot#588]
Is there a way to pass a wildcard as yang files instead of passing all the files names in a list?
generator -output_file=<outputpath> -package_name=<pkg> [yangfiles]

**Comment by adelshafiei** [comment]
I figured I can do a *, however, * includes the folders and files. How can I just pass the files?

**Comment by wenovus** [comment]
ygot doesn't have this feature but maybe bash's `find` will help?

**Comment by adelshafiei** [comment]
yes bash commands are the solution. Thanks
