### ISSUE TITLE
When using the option -generate_populate_defaults, depending on the default value syntax, code is not generated correctly

### ISSUE THREAD

**Issue by hansthienpondt** [openconfig/ygot#628]
Considering the following [yang model](https://github.com/openconfig/ygot/files/8314732/enum.yang.txt),

When generating ygot code using
```
//go:generate bash -c "/home/hans/git/ygot/generator/generator -output_file=/home/hans/tmp/bug/ygot.go -package_name=enumygot -generate_fakeroot -fakeroot_name device -path=yang/ -typedef_enum_with_defmod  -shorten_enum_leaf_names  -exclude_state -generate_simple_unions -generate_append -generate_delete -generate_getters -generate_populate_defaults /home/hans/git/fork-ygot/yang/enum.yang"
```

code seems to be generated incorrectly:
```
func (t *Uncompressed_Root) PopulateDefaults() {
        if (t == nil) {
                return
        }
        ygot.BuildEmptyTree(t)
        if t.NextHop ==  0 {
                t.NextHop = Uncompressed_NextHopType_use-system-ipv4-address
        }
}
``` 
Notice t.NextHop (Uncompressed_NextHopType_**use-system-ipv4-address**) does not equal the correct constant Uncompressed_NextHopType_**use_system_ipv4_address**

I think this might be related to either:
- https://github.com/openconfig/ygot/blob/master/ygen/gogen.go#L1308
- https://github.com/openconfig/ygot/blob/master/ygen/goelements.go#L546

In a workaround I've applied https://github.com/openconfig/ygot/blob/master/ygen/helpers.go#L36 to the string, which performs  necessary string replace functions and makes sure the variable is resolved in the generated code.

I've only tested this single use case so far, so will update this issue when I have more info and/or more use-cases.

**Comment by hansthienpondt** [comment]
Thanks for the confirmation, I'll submit a PR!
Do you have any pointers to test-cases that I should add? Potentially here? https://github.com/openconfig/ygot/blob/c23842204c73a8c452b593ddc931ebcdaa580372/ygen/gogen_test.go#L2372

As for the PR, do you expect it to be sanitised while executing  
https://github.com/openconfig/ygot/blob/c23842204c73a8c452b593ddc931ebcdaa580372/ygen/helpers.go#L79

or do you expect it to be sanitised when calling
https://github.com/openconfig/ygot/blob/c23842204c73a8c452b593ddc931ebcdaa580372/ygen/goelements.go#L650

**Comment by wenovus** [comment]
The sanitizing should happen in `enumDefaultValue()` since we expect the input to this function to be `prefix:value` per the function's doc comments. This will also fix things in other places where we call this function.

For testing since `goLeafDefaults()` will be deprecated for v1 it'll be better to test here: https://github.com/openconfig/ygot/blob/c23842204c73a8c452b593ddc931ebcdaa580372/ygen/goelements_test.go#L1418

If you just modify a few test cases for enums (`inValue`) and identityrefs (search for `values: []`) that should be sufficient, thanks!

**Comment by hansthienpondt** [comment]
Alright, thanks! 
I'll submit a PR asap!
