### ISSUE TITLE
JSON Marshal functions shouldn't prepend the module name for in-namespace fields of a non-root-level GoStruct

### ISSUE THREAD

**Issue by wenovus** [openconfig/ygot#637]
ConstructIETFJSON, Marshal7951, EmitJSON currently always initializes the `parentMod` to `""` when marshalling a GoStruct, regardless of whether it is the fake root or not. This means that for non-root-level GoStructs, all fields have their belonging-module's name prepended in their JSON object-member names. This appears to violate RFC7951:

```
   Every data node instance is encoded as a name/value pair where the
   name is formed from the data node identifier using the rules of
   [Section 4](https://datatracker.ietf.org/doc/html/rfc7951#section-4).
   The value depends on the category of the data node, as
   explained in the following subsections.
```
([ref](https://datatracker.ietf.org/doc/html/rfc7951#section-5))

One way to solve this is by adding a method (e.g. `ΛBelongingModule()`) to each GoStruct to determine its belonging-module, such that we can treat lower-level structs differently when marshalling GoStructs.

@robshakir would be good to get your thoughts on this one before we fix this. The RFC doesn't provide a very clear example of it but I think it's fair to interpret it this way.

**Comment by cprabha** [comment]
Hi,

Is there any workaround to run scripts until this is supported?
I am trying to run bgp scripts and have this issue. openconfig-network-instances is not prepended and script fails.

Thanks,
Prabha

**Comment by wenovus** [comment]
Hi, I will get to this this week, although this problem is when the module is prepend too much rather than too little.

**Comment by cprabha** [comment]
Thank you.

**Comment by robshakir** [comment]
Interesting, I presume that this happens if you call marshal for a child struct, but not from the parent. This does sound like a defect from the RFC you referenced. I'll take a look at the code change.
