### ISSUE TITLE
Unable to use ygot stubs to fetch state with optional attribute ( path-id) part of the key for unicast BGP route.

### ISSUE THREAD

**Issue by apratimmukherjee** [openconfig/ygot#715]
We are facing some issues when trying to use generated ygot stubs to fetch BGP routes with path-id not present where path-id is part of the key.
We have our own variant of the gnmi definition but attempt to keep it similar to open-config .
https://github.com/open-traffic-generator/models-yang/blob/main/artifacts/open-traffic-generator-bgp.txt
[Note: Due to this issue , this does not yet have path-id as the key for BGP routes]

The corresponding open-config definition for BGP rib/route fetch we are trying to implement is defined as below.
The peculiarity with this is that though prefix + origin + path-id is the key for a BGP routes, the path-id itself is an optional parameter in the route itself being fetched.
```
     
        |     +--ro afi-safis
              |        +--ro afi-safi* [afi-safi-name]
              |           +--ro afi-safi-name       -> ../state/afi-safi-name
              |           +--ro state
              |           |  +--ro afi-safi-name?   identityref
              |           +--ro ipv4-unicast
              |           |  +--ro loc-rib
              |           |  |  +--ro state
              |           |  |  +--ro routes
              |           |  |     +--ro route* [prefix origin path-id]  <<<< path-id is correctly part of the key but might be missing in the route. 
              |           |  |        +--ro prefix                -> ../state/prefix
              |           |  |        +--ro origin                -> ../state/origin
              |           |  |        +--ro path-id               -> ../state/path-id <<<<
              |           |  |        +--ro state
              |           |  |        |  +--ro prefix?                        oc-inet:ipv4-prefix
	      |           |  |        |  +--ro origin?                        union
              |           |  |        |  +--ro path-id?                       uint32   <<<<<< optional parameter in BGP route so could be missing 

```
              
However , when we have path-id as part of the key in similar fashion in our gnmi model , the stubs generated by ygot add a check that path-id should NOT be null.

```
func (t *BgpPeer) AppendUnicastIpv4Prefix(v* BgpPeer_UnicastIpv4Prefix) error {
    if v.Address = nil {
    	return fmt.Errorf("invalid nil key for Address")
    }
    
    if v.PrefixLength = nil {
        	return fmt.Errorf("invalid nil key for PrefixLength")
    }
    
    if v.PathId = nil {
            	return fmt.Errorf("invalid nil key for PathId") <<<<
    }
    ...
}
```

Now, when we have a rib where routes are present without optional path-id , those routes are not fetched due to the auto-generated code rejecting the routes which dont have path-id due to the check added where each parameter is expected to be non-null.
The question is : Are we mistake in understanding the way the model should be defined in this case or  Is this behaviour of ygot incorrect and should it somehow be able to handle missing path-id in the route ?
If we remove path-id from the key instead and have say 3 routes with same prefix and origin but different path-ids , then only one route is fetched and not all which is when having path-id as part of key becomes important.

**Comment by wenovus** [comment]
https://github.com/openconfig/public/blob/fca8ed94d57452064744f9a7352c24476febfbb2/release/models/rib/openconfig-rib-bgp-tables.yang#L177-L188
By optional do you mean it should be 0?

**Comment by wenovus** [comment]
https://datatracker.ietf.org/doc/html/rfc7950#section-7.8.2
```
   The combined values of all the leafs specified in the key are used to
   uniquely identify a list entry.  All key leafs MUST be given values
   when a list entry is created.  Thus, any default values in the key
   leafs or their types are ignored.  Any "mandatory" statements in the
   key leafs are ignored.
```

**Comment by apratimmukherjee** [comment]
Thanks a lot  for the quick response. Indeed , we missed the fact that though path-id is optional, it should be assigned a default value of 0 to be able to use it as part of the key.
