### ISSUE TITLE
update.sh script not generating bgp rib proto/go files after ribproto file is removed

### ISSUE THREAD

**Issue by babuveld** [openconfig/ygot#743]
Can you let me know how below the protofiles/go files got generated for bgp rib from the demo directory? Looks like it was checked in code and not generated? 

BGP RIB directory: https://github.com/openconfig/ygot/tree/master/demo/protobuf_getting_started/ribproto/openconfig/openconfig_rib_bgp 

Below is what I did and I don't see the bgp rib proto files.

[1] I downloaded the latest OC public models to directory https://github.com/openconfig/ygot/tree/master/demo/protobuf_getting_started/yang

[2] Removed directory https://github.com/openconfig/ygot/tree/master/demo/protobuf_getting_started/ribproto to check if it gets generated.

[3] Executed update.sh script https://github.com/openconfig/ygot/blob/master/demo/protobuf_getting_started/update.sh and I don't see folder "ribproto/openconfig)/openconfig_rib_bgp" getting generated.

```
root@ed0b0a555225:~/github.com/openconfig/ygot/demo/protobuf_getting_started# pwd
/root/github.com/openconfig/ygot/demo/protobuf_getting_started
root@ed0b0a555225:~/github.com/openconfig/ygot/demo/protobuf_getting_started# rm -rf ribproto/
root@ed0b0a555225:~/github.com/openconfig/ygot/demo/protobuf_getting_started# tree ribproto/
ribproto/ [error opening dir]

0 directories, 0 files
root@ed0b0a555225:~/github.com/openconfig/ygot/demo/protobuf_getting_started# ./update.sh
protoc -I=.:../../../../../ --go_out=. --go_opt=paths=source_relative ribproto/openconfig/openconfig.proto
root@ed0b0a555225:~/github.com/openconfig/ygot/demo/protobuf_getting_started# tree ribproto/
ribproto/
`-- openconfig
    |-- openconfig.pb.go
    `-- openconfig.proto

1 directory, 2 files
root@ed0b0a555225:~/github.com/openconfig/ygot/demo/protobuf_getting_started#

```

**Comment by wenovus** [comment]
I'm not sure, I am seeing essentially the same tree (except the pkg.go is not generated) after I run update.sh.

I don't think you need to do step [1] since the YANG files are already in yang/ to avoid upstream breaking this demo code. Maybe that's what's causing your issues.

**Comment by babuveld** [comment]
Thanks for the quick response.
