### ISSUE TITLE
enable debug logs for protogenerator.go

### ISSUE THREAD

**Issue by babuveld** [openconfig/ygot#745]
Hi,

If I update the bgp rib yang files under https://github.com/openconfig/ygot/tree/master/demo/protobuf_getting_started/yang and run protogenerator.go, I don't see the new protofile getting generated. Can you let me know how I can enable debug logs for protogenerator.go so I can check if there are any errors?

generator doesn't return any errormsg and also the exit code for the script is 0.

**Comment by babuveld** [comment]
Can someone help with the query please.

**Comment by wenovus** [comment]
Did you run https://github.com/openconfig/ygot/blob/master/demo/protobuf_getting_started/update.sh?

**Comment by babuveld** [comment]
yes. I ran the script.

**Comment by wenovus** [comment]
If I add a test container to demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang I can see it after running update.sh. Do you have a reproducing diff?

```diff
diff --git a/demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang b/demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang
index 1af876b..b1e10b6 100644
--- a/demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang
+++ b/demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang
@@ -103,6 +103,13 @@ module openconfig-rib-bgp {
     description
       "Top-level grouping for the BGP RIB";
 
+    container test-container {
+      config false;
+      leaf test-leaf {
+        type string;
+      }
+    }
+
     container bgp-rib {
       config false;
       description
```

```diff
diff --git a/demo/protobuf_getting_started/ribproto/openconfig/openconfig.pb.go b/demo/protobuf_getting_started/ribproto/openconfig/openconfig.pb.go
index a37787e..8f34809 100644
--- a/demo/protobuf_getting_started/ribproto/openconfig/openconfig.pb.go
+++ b/demo/protobuf_getting_started/ribproto/openconfig/openconfig.pb.go
@@ -35,7 +35,8 @@ type Device struct {
        sizeCache     protoimpl.SizeCache
        unknownFields protoimpl.UnknownFields
 
-       BgpRib *openconfig_rib_bgp.BgpRib `protobuf:"bytes,314942212,opt,name=bgp_rib,json=bgpRib,proto3" json:"bgp_rib,omitempty"`
+       BgpRib        *openconfig_rib_bgp.BgpRib        `protobuf:"bytes,314942212,opt,name=bgp_rib,json=bgpRib,proto3" json:"bgp_rib,omitempty"`
+       TestContainer *openconfig_rib_bgp.TestContainer `protobuf:"bytes,4819359,opt,name=test_container,json=testContainer,proto3" json:"test_container,omitempty"`
 }
 
 func (x *Device) Reset() {
```

**Comment by babuveld** [comment]
Thanks for getting back. Please find the steps and commands I used below.

`[1] Pull the latest ygot and yang git repo:
============================================
root@a6fdb7117f36:/go/src/github.com/openconfig# pwd
/go/src/github.com/openconfig
root@a6fdb7117f36:/go/src/github.com/openconfig# ls
root@a6fdb7117f36:/go/src/github.com/openconfig#
root@a6fdb7117f36:/go/src/github.com/openconfig# git clone https://github.com/openconfig/ygot.git
Cloning into 'ygot'...
remote: Enumerating objects: 8372, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 8372 (delta 44), reused 78 (delta 31), pack-reused 8248
Receiving objects: 100% (8372/8372), 120.81 MiB | 9.97 MiB/s, done.
Resolving deltas: 100% (6006/6006), done.
root@a6fdb7117f36:/go/src/github.com/openconfig#
root@a6fdb7117f36:/go/src/github.com/openconfig# git clone https://github.com/openconfig/public.git
Cloning into 'public'...
remote: Enumerating objects: 4314, done.
remote: Counting objects: 100% (328/328), done.
remote: Compressing objects: 100% (229/229), done.
remote: Total 4314 (delta 168), reused 207 (delta 99), pack-reused 3986
Receiving objects: 100% (4314/4314), 2.52 MiB | 8.14 MiB/s, done.
Resolving deltas: 100% (2552/2552), done.
root@a6fdb7117f36:/go/src/github.com/openconfig# ls
public	ygot
root@a6fdb7117f36:/go/src/github.com/openconfig#

root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models# ls -ltr /go/src/github.com/openconfig/ygot/demo/protobuf_getting_started/yang/rib/
total 60
-rw-r--r-- 1 root root  2619 Nov 30 21:23 openconfig-rib-bgp-table-attributes.yang
-rw-r--r-- 1 root root  4082 Nov 30 21:23 openconfig-rib-bgp-shared-attributes.yang
-rw-r--r-- 1 root root  4893 Nov 30 21:23 openconfig-rib-bgp-ext.yang
-rw-r--r-- 1 root root 12299 Nov 30 21:23 openconfig-rib-bgp-attributes.yang
-rw-r--r-- 1 root root  4867 Nov 30 21:23 openconfig-rib-bgp.yang
-rw-r--r-- 1 root root  3775 Nov 30 21:23 openconfig-rib-bgp-types.yang
-rw-r--r-- 1 root root 16057 Nov 30 21:23 openconfig-rib-bgp-tables.yang
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models#

root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models# ls -ltr /go/src/github.com/openconfig/ygot/demo/protobuf_getting_started/yang/deps
total 104
-rw-r--r-- 1 root root 16772 Nov 30 21:23 ietf-inet-types.yang
-rw-r--r-- 1 root root  7746 Nov 30 21:23 openconfig-types.yang
-rw-r--r-- 1 root root  4595 Nov 30 21:23 openconfig-policy-types.yang
-rw-r--r-- 1 root root 10858 Nov 30 21:23 openconfig-inet-types.yang
-rw-r--r-- 1 root root  2951 Nov 30 21:23 openconfig-extensions.yang
-rw-r--r-- 1 root root 18002 Nov 30 21:23 openconfig-bgp-types.yang
-rw-r--r-- 1 root root 11179 Nov 30 21:23 openconfig-bgp-errors.yang
-rw-r--r-- 1 root root 17863 Nov 30 21:23 ietf-yang-types.yang
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models#

[2] Copy the rib and other dependency models from oc to ygot:
==============================================================
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models/rib# pwd
/go/src/github.com/openconfig/public/release/models/rib
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models/rib#
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models/rib# cp openconfig-rib-bgp-table-attributes.yang openconfig-rib-bgp-shared-attributes.yang openconfig-rib-bgp-ext.yang openconfig-rib-bgp-attributes.yang openconfig-rib-bgp.yang openconfig-rib-bgp-types.yang openconfig-rib-bgp-tables.yang /go/src/github.com/openconfig/ygot/demo/protobuf_getting_started/yang/rib/
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models/rib#
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models/rib# ls -ltr /go/src/github.com/openconfig/ygot/demo/protobuf_getting_started/yang/rib
total 116
-rw-r--r-- 1 root root  7135 Nov 30 21:30 openconfig-rib-bgp.yang
-rw-r--r-- 1 root root  3571 Nov 30 21:30 openconfig-rib-bgp-table-attributes.yang
-rw-r--r-- 1 root root  5094 Nov 30 21:30 openconfig-rib-bgp-shared-attributes.yang
-rw-r--r-- 1 root root  6305 Nov 30 21:30 openconfig-rib-bgp-ext.yang
-rw-r--r-- 1 root root 28764 Nov 30 21:30 openconfig-rib-bgp-attributes.yang
-rw-r--r-- 1 root root  6848 Nov 30 21:30 openconfig-rib-bgp-types.yang
-rw-r--r-- 1 root root 48880 Nov 30 21:30 openconfig-rib-bgp-tables.yang
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models/rib# 
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models# pwd
/go/src/github.com/openconfig/public/release/models
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models#
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models# cp ./types/openconfig-types.yang ./policy/openconfig-policy-types.yang ./types/openconfig-inet-types.yang ./openconfig-extensions.yang ./bgp/openconfig-bgp-types.yang ./bgp/openconfig-bgp-errors.yang ./segment-routing/openconfig-segment-routing-types.yang ./mpls/openconfig-mpls-types.yang ./types/openconfig-yang-types.yang ./network-instance/openconfig-network-instance-types.yang ./network-instance/openconfig-evpn-types.yang /go/src/github.com/openconfig/ygot/demo/protobuf_getting_started/yang/deps/
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models# ls -ltr /go/src/github.com/openconfig/ygot/demo/protobuf_getting_started/yang/deps/
total 128
-rw-r--r-- 1 root root 16772 Nov 30 21:23 ietf-inet-types.yang
-rw-r--r-- 1 root root 17863 Nov 30 21:23 ietf-yang-types.yang
-rw-r--r-- 1 root root 12172 Nov 30 21:33 openconfig-types.yang
-rw-r--r-- 1 root root  6593 Nov 30 21:33 openconfig-policy-types.yang
-rw-r--r-- 1 root root 15173 Nov 30 21:33 openconfig-inet-types.yang
-rw-r--r-- 1 root root  7183 Nov 30 21:33 openconfig-extensions.yang
-rw-r--r-- 1 root root 26471 Nov 30 21:33 openconfig-bgp-types.yang
-rw-r--r-- 1 root root 12534 Nov 30 21:33 openconfig-bgp-errors.yang
root@a6fdb7117f36:/go/src/github.com/openconfig/public/release/models#

[3] Run the update.sh script:  [Script runs successfully and no errors, however the proto is not regenerated.]
==============================
root@a6fdb7117f36:/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started# pwd
/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started
root@a6fdb7117f36:/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started# ls -ltr ./ribproto/openconfig/openconfig_rib_bgp/openconfig_rib_bgp.proto
-rw-r--r-- 1 root root 66055 Nov 30 21:23 ./ribproto/openconfig/openconfig_rib_bgp/openconfig_rib_bgp.proto
root@a6fdb7117f36:/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started#

root@a6fdb7117f36:/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started# ./update.sh
protoc -I=.:../../../../../ --go_out=. --go_opt=paths=source_relative ribproto/openconfig/openconfig_rib_bgp/openconfig_rib_bgp.proto
protoc -I=.:../../../../../ --go_out=. --go_opt=paths=source_relative ribproto/openconfig/openconfig.proto
protoc -I=.:../../../../../ --go_out=. --go_opt=paths=source_relative ribproto/openconfig/enums/enums.proto
root@a6fdb7117f36:/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started# echo $?
0
root@a6fdb7117f36:/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started# ls -ltr ribproto/openconfig/openconfig_rib_bgp/openconfig_rib_bgp.proto
-rw-r--r-- 1 root root 66055 Nov 30 21:23 ribproto/openconfig/openconfig_rib_bgp/openconfig_rib_bgp.proto
root@a6fdb7117f36:/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started# date
Wed Nov 30 21:38:47 UTC 2022
root@a6fdb7117f36:/go/src/github.com/openconfig/ygot/demo/protobuf_getting_started#


`

**Comment by wenovus** [comment]
Could you post a fork of your repo containing all of the changed files?

**Comment by babuveld** [comment]
Can you please use this forked repo with updated models. https://github.com/babuveld/ygot.git

**Comment by wenovus** [comment]
Thanks for uploading the fork.

The reason you're not seeing anything is because in the latest version of this YANG, there is no instantiation at the top-level of the module. As a result there is no reason to re-generate any part of the model in proto:

`git show demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang`

```diff
diff --git a/demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang b/demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang
index 1af876b..d2d5f27 100644
--- a/demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang
+++ b/demo/protobuf_getting_started/yang/rib/openconfig-rib-bgp.yang
@@ -170,9 +254,6 @@ module openconfig-rib-bgp {
 
 
   // data definition statements
-
-  uses bgp-rib-top;
-
   // augment statements
```

Indeed, if you `rm -r ribproto`  and then re-generate, you will see that most of the proto files don't even get created. This is not the case prior to you copying the latest version of the models.

**Comment by babuveld** [comment]
Thanks for the inputs. Yes that you are right. Does this mean we cannot generate proto files for the openconfig-bgp-rib models because uses statement missing?

I tried adding the above statement for test purpose and could see new proto files got generated.

**Comment by wenovus** [comment]
You need to use the right model. Search for "uses bgp-rib-top" in the openconfig models.
