### ISSUE TITLE
Compressed GoStructs doesn't support same-name lists under different-name containers

### ISSUE THREAD

**Issue by wenovus** [openconfig/ygot#750]
```YANG
module a {
  prefix a;
  namespace a.com;

  container aa {
    list a {
      key a;
      leaf a {
        type leafref {
          path "../config/a";
        }
      }
      container config {
        leaf a {
          type string;
        }
      }
      container state {
        leaf a {
          type string;
        }
      }
    }
  }

  container bb {
    list a {
      key a;
      leaf a {
        type leafref {
          path "../config/a";
        }
      }
      container config {
        leaf a {
          type string;
        }
      }
      container state {
        leaf a {
          type string;
        }
      }
    }
  }
}
```
```
ERROR Generating GoStruct Code: duplicate entry a at the root: exists: /a/aa/a, new: /a/bb/a
```
If an extra container at the root is added, then we get
```
ERROR Generating GoStruct Code: /a/a/bb/a was duplicate
```

**Comment by wenovus** [comment]
From what I can see right now supporting this will involve two steps:
1. Change ygen handing of the structs map in `createFakeRoot` as well as `Directory.Fields/ShadowFields` to be keyed on the full relative path of the node when list path compression is involved (e.g. `acl-sets/acl-set`). The downstream effect is that we need to change usages of the name as the YANG name to the actual field containing the YANG name. The majority of the change involves `ParsedDirectory.Fields`, where downstream code needs to reference YANGDetails.Name instead of using the map key directly.
2. Changing `GoLangMapper.DirectoryName` to deal with such relative paths (e.g. `acl-sets/acl-set`) such that the generated name is unique. The simplest way is to concatenate the two elements as camel case names. This would mean code generated using this flag is backward-incompatible with code not generated using this flag since it is much more verbose. An easy tweak is to check for the common pattern of (names/name) and skip the first name on recognition.

**Comment by robshakir** [comment]
This is enforced by the linter: https://github.com/openconfig/oc-pyang/tree/master/tests/oclinter/lists-compression

I don't think we should make changes to support this. Where is it occurring?

**Comment by wenovus** [comment]
Thanks for the reference. I'm looking at some vendor models, I'll ping you offline.

**Comment by wenovus** [comment]
I agree this should not be supported.
