### ISSUE TITLE
Generator options and `structs_split_files_count`

### ISSUE THREAD

**Issue by n0shut** [openconfig/ygot#768]
👋 all,
I see that in the generator flags we mention that `structs_split_files_count` works only when `output_file` is specified.

https://github.com/openconfig/ygot/blob/faf395436e2fae19420fa3638114ddfb1909bea5/generator/generator.go#L58

But I think the description is false, because we actually need to not use `output_file` and use `output_dir` instead.

If you agree with that, I can file a PR with fixing the flag description.

**Comment by wenovus** [comment]
That would be great, thanks!

Could you fix the description for `path_structs_split_files_count` as well? For that flag `split_pathstructs_by_module` should also enable this behaviour, thanks!
