### ISSUE TITLE
ygot does not support default integer values expressed in hexadecimal format

### ISSUE THREAD

**Issue by dbourkey** [openconfig/ygot#790]
I came across this error when running the generator (v0.26.0) against the adtran-xpon.yang model which contained leafnodes in the following format:

`
      leaf name-of-leaf {
        type uint16;
        default 0x8100;
        description
          "...";
      }
`

` $ ~/bin/generator -ignore_unsupported -path=adtran_yang -output_file=adtran_yang.go -package_name=adtran_yang adtran_yang/adtran-xpon.yang
F0304 22:56:10.747789   65264 generator.go:382] ERROR Generating GoStruct Code: default value conversion: unable to convert default value "0x8100" to uint16: strconv.ParseUint: parsing "0x8100": invalid syntax
`

May I ask, was there an intentional decision to not support hexedecimal?

Fix would be simple enough.

**Comment by wenovus** [comment]
Apologies for the late reply. Thanks @jayzhudev for the fix. I think this should be working now.
