### ISSUE TITLE
Code generated for enums does not use the value defined in the YANG

### ISSUE THREAD

**Issue by ythadhani** [openconfig/ygot#812]
**Example YANG:**
leaf test {
       type enumeration {
              enum "disabled" {value 5;}
              enum "enabled" {value 9;}
       }
}

**Generated Go Code**(variable names shortened for simplicity):
const (
	UNSET E_Test = 0
	disabled E_Test = 1
        enabled E_Test= 2
)

**The Go code that I expect:**
const (
	UNSET E_Test = 0
	disabled E_Test = 6
        enabled E_Test= 10
)

This seems to have been introduced somewhere in: https://github.com/openconfig/ygot/compare/v0.16.3...v0.19.0#diff-bb557ab977ac36a97197943544b87027a42d0a7d35c27b7866b62273ea4b76b1 because v0.16.3 was working as expected.

We seem to be using the slice index during iteration instead of the Value inside the EnumDefinition: https://github.com/openconfig/ygot/blob/master/gogen/codegen.go#L389-L390

Is this a bug or am I missing something here?

**Comment by wenovus** [comment]
Thanks for reporting this, this is indeed a bug and I'll take a look at fixing it.
