### ISSUE TITLE
`slices.SortFunc`'s `cmp` function uses wrong return type

### ISSUE THREAD

**Issue by jayzhudev** [openconfig/ygot#896]
I noticed that the change in #894 uses `slices.SortFunc` with `bool` as the `cmp` function's return type which seems to be inconsistent compared to what I saw in the docs and in the standard library source code.

Both of the following use `int` as the return type
- Go `master` branch: <https://github.com/golang/go/blob/master/src/slices/sort.go#L28>
- <https://pkg.go.dev/golang.org/x/exp/slices#SortFunc>

This change also seems to break support for the latest 3 Go release.

Thank you!

**Comment by wenovus** [comment]
Thanks Jay, we have just fixed this here: https://github.com/openconfig/ygot/releases/tag/v0.29.5

**Comment by jayzhudev** [comment]
> Thanks Jay, we have just fixed this here: https://github.com/openconfig/ygot/releases/tag/v0.29.5

That's awesome, thanks!
