### ISSUE TITLE
how to resolve the dependency for gribi

### ISSUE THREAD

**Issue by snackwell** [openconfig/ygot#913]
when run command "go mod tidy: meet below error:
go: github.com/openconfig/ygot@v0.26.2 requires
        github.com/openconfig/gribi@v0.1.1-0.20221218044856-ec9f4fc18013: invalid version: unknown revision ec9f4fc18013

So... How to deal with it?

**Comment by wenovus** [comment]
Hmm. Are you experiencing this in a different repo that imports ygot? v0.26.2 is an older version, are you able to use a newer version of ygot to try to work around the issue? The current ygot version uses gribi@v1.0.0

**Comment by snackwell** [comment]
> Hmm. Are you experiencing this in a different repo that imports ygot? v0.26.2 is an older version, are you able to use a newer version of ygot to try to work around the issue? The current ygot version uses gribi@v1.0.0

It works. Thanks
