### ISSUE TITLE
invalid module name prefix in IETF JSON

### ISSUE THREAD

**Issue by larryleguo** [openconfig/ygot#92]
ygot.ConstructIETFJSON() can generate the following JSON config:

{
  "openconfig-system:openconfig-openflow:system": {
    "openflow": {
      "agent": {
        "config": {
          "backoff-interval": 5,
          "datapath-id": "00:16:3e:00:00:00:00:00",
          "failure-mode": "SECURE",
          "inactivity-probe": 10,
          "max-backoff": 10
        }
      }
    }
  },
  "openconfig-system:system": {
    "clock": {
      "config": {
        "timezone-name": "Europe/Stockholm"
      }
    },
    "config": {
      "domain-name": "google.com",
      "hostname": "switch_a",
      "login-banner": "Hello!",
      "motd-banner": "Hi There!"
    }
  }
}

The first "system" section contains more than one module name as a prefix.
However, according toRFC 7951 section 4 “Names and Namespaces”, this is invalid:
there can only be a single module name preceding the element name.

**Comment by robshakir** [comment]
Confirmed fixed in: https://groups.google.com/forum/#!topic/ygot-users/TeyRrRGTgKA
